spring:
  application.name: pos
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        highlight_sql: true
        show_sql: false
        jdbc.batch_size: 1000
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    #    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: TRACE
    p6spy: debug
#    org.springframework: trace

jwt:
  secret: aGVsbG93b3JsZGhlbGxvd29ybGRoZWxsb3dvcmxkMTIz
  access-expiration: 30 # minute
  refresh-expiration: 10080 # minute 7일
---
spring.config.activate.on-profile: default

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console